### PR TITLE
Resolved validation issue on set temperature point method.

### PR DESCRIPTION
**Pull request by Cinntax**
Sorry- I was doing last minute testing prior to doing my pull request for hass, and ran into this issue.  Looking closely at the API- this check only applies if you're running the system in "auto" mode- not if in heat/cool mode.  So i adjusted this validation.   Can we do a 0.3 so i can push the hass component?

### CODE REVIEW

**Comment by hpeyerl** [comment]
ok. done.  0.3 is pushed to pypi.

**Comment by Cinntax** [comment]
great thanks!  https://github.com/home-assistant/home-assistant/pull/11639

**Comment by hpeyerl** [comment]
Good luck.  I dropped the ball on one I did earlier in the year:

https://github.com/home-assistant/home-assistant/pull/8900

Never got back to it.

**Comment by Cinntax** [comment]
Thanks- yeah I usually go through a few iterations. Usually it’s because the internals of hass are constantly undergoing improvements, and so when I rarely submit something, I’m not usually following those latest standards. Well see

**Pull request merged**
