### PR TITLE
The model check broke my venstar

### PR DESCRIPTION
**Pull request by garbled1**
This defaults it to the COLORTOUCH if "model" isn't present.  (it's not on v3 api, but everything else works, so, whatever)

### CODE REVIEW

**Comment by garbled1** [comment]
Pulled down latest, tested against my venstars.  (an api3 and an api7).  This patch makes it work on both.

**Comment by hpeyerl** [comment]
Thanks.  Pushed a 0.12 to pypi.

btw, our homelabs are eerily similar.   Have you checked out emoncms and https://openenergymonitor.org ?

**Comment by garbled1** [comment]
Ha.  I have a brultech GEM.  :)  I have a zero-cloud policy, and I suspect you do too, so that lends to us buying the same stuff.
Right now my stack is:

3 Venstars
1 Brultech GEM (greeneye)
Insteon
2 onewire trees
ademco alarm panel (and ad2usb)
A half-broken WMR968 weather station
IrrigationCaddy
Balboa SPA (wifi)
A bunch of DIY ESP8266/RPI sensors.

I've spent years doing my own home automation (gnhast), and in alot of ways it's still superior to hass, but I think I can fix my way out of that in hass. I'm sick of maintaining an entire engine and ecosystem.  I spend more time writing backend code than I do writing automation.

**Comment by hpeyerl** [comment]
I have a near-zero cloud tolerance policy.  I accept Plex for what it is.

2 sites, 3 buildings.  Synology NAS, Venstar, Etherrain/8, Zoneminder, a bunch of esp8266 home-built sensors/switches, tplink switches, airthingswave, emonpi/emontx, apcupsd, proxmox, pfsense. A smattering of APRS for when the internet connection disappears.

I also went down the roll-my-own home automation with a ton of back-end scripts with mysql and I dabbled in using Snap for drag&drop automation.  It was working well but then homeassistant appeared and supported most of what I need.  The automation programming sucks balls but I don't have the energy to improve it.

btw, none of the obvious email addresses for you worked so I couldn't take this to private. If you want contact me through my NB address to take this out of public.

**Pull request merged**
