### PR TITLE
Improve handling of sensors when remote sensors are in use

### LINKED ISSUE #21: No support for remote interior sensors
This is a bit more complex, so if I get to it, might be a few weeks.

My device has a remote sensor. My remote sensor is set as an alternate interior sensor.  This makes things extra fun apparently:

```
{"name":"Cave","mode":3,"state":0,"fan":0,"fanstate":0,
"tempunits":0,"schedule":0,"schedulepart":255,"away":0,
"spacetemp":77.0,"heattemp":72.0,"cooltemp":79.0,
"cooltempmin":35.0,"cooltempmax":99.0,"heattempmin":35.00,
"heattempmax":99.0,"activestage":0,"hum_active":0,"hum":50,
"hum_setpoint":0,"dehum_setpoint":99,"setpointdelta":2.0,"availablemodes":0}

{"sensors":[{"name":"Thermostat","temp":77.0,"hum":50},
{"name":"Space Temp","temp":77.0},
{"name":"Remote","temp":76.0}]}
```

I'm leaving this here for a bit in case anyone wants to tackle, otherwise I might take a crack at it.. it would involve some refactoring...  (Space temp is an average of Thermostat and Remote)

### PR DESCRIPTION
**Pull request by doug-hoffman**
Corrects previous behavior that unconditionally treated sensor 0 as indoor and sensor 1 as outdoor. When using any sensor other than the internal temperature sensor as the control source, sensor 1 becomes the control temperature, and sensor 2 the outdoor. Sensors are now matched by name with "Space Temp" used as the indoor temperature when present, and "Thermostat" when it is not. API documentation gives no indication that these names differ based on region or language, so there is no obvious reason to believe they shouldn't remain consistent.

Also appears to resolve #21.

```
Testing with IP: 192.168.123.45
logging in...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET / HTTP/1.1" 200 None
Login successful. API: 9 Type: residential
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Was able to get info:{'name': 'Living Room', 'mode': 1, 'state': 0, 'fan': 0, 'fanstate': 0, 'tempunits': 0, 'schedule': 0, 'schedulepart': 255, 'away': 0, 'spacetemp': 73.0, 'heattemp': 73.0, 'cooltemp': 82.0, 'cooltempmin': 35.0, 'cooltempmax': 99.0, 'heattempmin': 35.0, 'heattempmax': 99.0, 'activestage': 0, 'hum_active': 0, 'hum': 40, 'hum_setpoint': 45, 'dehum_setpoint': 55, 'setpointdelta': 2.0, 'availablemodes': 0}
Name is Living Room
Fan is 0
Heat setpoint is 73.0
Cool setpoint is 82.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/sensors HTTP/1.1" 200 None
Was able to get sensors:{'sensors': [{'name': 'Thermostat', 'temp': 74.0, 'hum': 40}, {'name': 'Space Temp', 'temp': 73.0}, {'name': 'Outdoor', 'temp': 48.0}, {'id': 18, 'name': 'HVAC Supply', 'temp': 80.0, 'battery': 100, 'type': 'Supply'}, {'id': 19, 'name': 'HVAC Return', 'temp': 70.0, 'battery': 100, 'type': 'Return'}, {'id': 0, 'name': 'Dining Room', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 1, 'name': 'Laundry Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 2, 'name': 'Master Bedroom', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 3, 'name': 'Master Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 4, 'name': 'Kitchen', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 5, 'name': 'Office', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 6, 'name': 'Guest Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 7, 'name': 'Guest Bedroom', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}]}
Indoor temp is 73.0 and humidity is 40
Outdoor temp is 48.0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/runtimes HTTP/1.1" 200 None
Runtimes: [{'ts': 1607299200, 'heat1': 146, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 13, 'aux2': 0, 'fc': 0}, {'ts': 1607385600, 'heat1': 455, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607472000, 'heat1': 369, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 20, 'aux2': 0, 'fc': 0}, {'ts': 1607558400, 'heat1': 492, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607644800, 'heat1': 352, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 19, 'aux2': 0, 'fc': 0}, {'ts': 1607731200, 'heat1': 318, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 36, 'aux2': 0, 'fc': 0}, {'ts': 1607781463, 'heat1': 237, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 24, 'aux2': 0, 'fc': 0}]
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 60.0
Cool setpoint is 90.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 73.0
Cool setpoint is 82.0
```

### CODE REVIEW

**Comment by garbled1** [comment]
It partially resolves my issue.  I think there is still no support for reading my second sensor, because it's not marked outdoor:

{"sensors":[{"name":"Thermostat","temp":77.0,"hum":20},{"name":"Space Temp","temp":77.0},{"name":"Remote","temp":76.0}]}

**Comment by doug-hoffman** [comment]
You can call get_sensors("Remote", "temp") to get that value. I just added get_sensor_list to enumerate sensor names. Is there something else you're specifically looking for?

```
Testing with IP: 192.168.123.45
logging in...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET / HTTP/1.1" 200 None
Login successful. API: 9 Type: residential
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Was able to get info:{'name': 'Living Room', 'mode': 1, 'state': 1, 'fan': 0, 'fanstate': 1, 'tempunits': 0, 'schedule': 0, 'schedulepart': 255, 'away': 0, 'spacetemp': 73.0, 'heattemp': 74.0, 'cooltemp': 82.0, 'cooltempmin': 35.0, 'cooltempmax': 99.0, 'heattempmin': 35.0, 'heattempmax': 99.0, 'activestage': 1, 'hum_active': 0, 'hum': 41, 'hum_setpoint': 45, 'dehum_setpoint': 55, 'setpointdelta': 2.0, 'availablemodes': 0}
Name is Living Room
Fan is 0
Heat setpoint is 74.0
Cool setpoint is 82.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/sensors HTTP/1.1" 200 None
Was able to get sensors:{'sensors': [{'name': 'Thermostat', 'temp': 74.0, 'hum': 41}, {'name': 'Space Temp', 'temp': 73.0}, {'name': 'Outdoor', 'temp': 48.0}, {'id': 18, 'name': 'HVAC Supply', 'temp': 109.0, 'battery': 100, 'type': 'Supply'}, {'id': 19, 'name': 'HVAC Return', 'temp': 72.0, 'battery': 100, 'type': 'Return'}, {'id': 0, 'name': 'Dining Room', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 1, 'name': 'Laundry Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 2, 'name': 'Master Bedroom', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 3, 'name': 'Master Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 4, 'name': 'Kitchen', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 5, 'name': 'Office', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 6, 'name': 'Guest Bath', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 7, 'name': 'Guest Bedroom', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}]}
Indoor temp is 73.0 and humidity is 41
Outdoor temp is 48.0

Thermostat temp is 74.0, humidity is 41, battery is None, and type is None
Space Temp temp is 73.0, humidity is None, battery is None, and type is None
Outdoor temp is 48.0, humidity is None, battery is None, and type is None
HVAC Supply temp is 109.0, humidity is None, battery is 100, and type is Supply
HVAC Return temp is 72.0, humidity is None, battery is 100, and type is Return
Dining Room temp is 73.0, humidity is None, battery is 100, and type is Remote
Laundry Bath temp is 73.0, humidity is None, battery is 100, and type is Remote
Master Bedroom temp is 73.0, humidity is None, battery is 100, and type is Remote
Master Bath temp is 73.0, humidity is None, battery is 100, and type is Remote
Kitchen temp is 73.0, humidity is None, battery is 100, and type is Remote
Office temp is 73.0, humidity is None, battery is 100, and type is Remote
Guest Bath temp is 73.0, humidity is None, battery is 100, and type is Remote
Guest Bedroom temp is 73.0, humidity is None, battery is 100, and type is Remote

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/runtimes HTTP/1.1" 200 None
Runtimes: [{'ts': 1607385600, 'heat1': 455, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607472000, 'heat1': 369, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 20, 'aux2': 0, 'fc': 0}, {'ts': 1607558400, 'heat1': 492, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607644800, 'heat1': 352, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 19, 'aux2': 0, 'fc': 0}, {'ts': 1607731200, 'heat1': 318, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 36, 'aux2': 0, 'fc': 0}, {'ts': 1607817600, 'heat1': 353, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 24, 'aux2': 0, 'fc': 0}, {'ts': 1607853105, 'heat1': 89, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 19, 'aux2': 0, 'fc': 0}]
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 60.0
Cool setpoint is 90.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 74.0
Cool setpoint is 82.0
```

**Comment by garbled1** [comment]
Aha, I understand, ok, thanks!

**Comment by doug-hoffman** [comment]
Ok, good to hear that'll work for you.

After some more thought, I added an optional filter for type to get_sensor_list and some logic to infer the sensor type for non-wireless sensors.

```
Testing with IP: 192.168.123.45
logging in...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET / HTTP/1.1" 200 None
Login successful. API: 9 Type: residential
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Was able to get info:{'name': 'Living Room', 'mode': 1, 'state': 3, 'fan': 0, 'fanstate': 0, 'tempunits': 0, 'schedule': 0, 'schedulepart': 255, 'away': 0, 'spacetemp': 73.0, 'heattemp': 74.0, 'cooltemp': 82.0, 'cooltempmin': 35.0, 'cooltempmax': 99.0, 'heattempmin': 35.0, 'heattempmax': 99.0, 'activestage': 1, 'hum_active': 0, 'hum': 40, 'hum_setpoint': 45, 'dehum_setpoint': 55, 'setpointdelta': 2.0, 'availablemodes': 0}
Name is Living Room
Fan is 0
Heat setpoint is 74.0
Cool setpoint is 82.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/sensors HTTP/1.1" 200 None
Was able to get sensors:{'sensors': [{'name': 'Thermostat', 'temp': 75.0, 'hum': 40}, {'name': 'Space Temp', 'temp': 73.0}, {'name': 'Outdoor', 'temp': 48.0}, {'id': 18, 'name': 'HVAC Supply', 'temp': 78.0, 'battery': 100, 'type': 'Supply'}, {'id': 19, 'name': 'HVAC Return', 'temp': 73.0, 'battery': 100, 'type': 'Return'}, {'id': 0, 'name': 'Dining Room', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 1, 'name': 'Laundry Bath', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 2, 'name': 'Master Bedroom', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 3, 'name': 'Master Bath', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 4, 'name': 'Kitchen', 'temp': 73.0, 'battery': 100, 'type': 'Remote'}, {'id': 5, 'name': 'Office', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 6, 'name': 'Guest Bath', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}, {'id': 7, 'name': 'Guest Bedroom', 'temp': 74.0, 'battery': 100, 'type': 'Remote'}]}
Indoor temp is 73.0 and humidity is 40
Outdoor temp is 48.0

All sensors:
Thermostat temp is 75.0, humidity is 40, battery is None, and type is Local
Space Temp temp is 73.0, humidity is None, battery is None, and type is Control
Outdoor temp is 48.0, humidity is None, battery is None, and type is Outdoor
HVAC Supply temp is 78.0, humidity is None, battery is 100, and type is Supply
HVAC Return temp is 73.0, humidity is None, battery is 100, and type is Return
Dining Room temp is 74.0, humidity is None, battery is 100, and type is Remote
Laundry Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Master Bedroom temp is 74.0, humidity is None, battery is 100, and type is Remote
Master Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Kitchen temp is 73.0, humidity is None, battery is 100, and type is Remote
Office temp is 74.0, humidity is None, battery is 100, and type is Remote
Guest Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Guest Bedroom temp is 74.0, humidity is None, battery is 100, and type is Remote

Control sensors:
Space Temp temp is 73.0, humidity is None, battery is None, and type is Control

Local sensors:
Thermostat temp is 75.0, humidity is 40, battery is None, and type is Local

Outdoor sensors:
Outdoor temp is 48.0, humidity is None, battery is None, and type is Outdoor

Remote sensors:
Dining Room temp is 74.0, humidity is None, battery is 100, and type is Remote
Laundry Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Master Bedroom temp is 74.0, humidity is None, battery is 100, and type is Remote
Master Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Kitchen temp is 73.0, humidity is None, battery is 100, and type is Remote
Office temp is 74.0, humidity is None, battery is 100, and type is Remote
Guest Bath temp is 74.0, humidity is None, battery is 100, and type is Remote
Guest Bedroom temp is 74.0, humidity is None, battery is 100, and type is Remote

Return sensors:
HVAC Return temp is 73.0, humidity is None, battery is 100, and type is Return

Supply sensors:
HVAC Supply temp is 78.0, humidity is None, battery is 100, and type is Supply

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/runtimes HTTP/1.1" 200 None
Runtimes: [{'ts': 1607385600, 'heat1': 455, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607472000, 'heat1': 369, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 20, 'aux2': 0, 'fc': 0}, {'ts': 1607558400, 'heat1': 492, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 0, 'aux2': 0, 'fc': 0}, {'ts': 1607644800, 'heat1': 352, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 19, 'aux2': 0, 'fc': 0}, {'ts': 1607731200, 'heat1': 318, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 36, 'aux2': 0, 'fc': 0}, {'ts': 1607817600, 'heat1': 353, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 24, 'aux2': 0, 'fc': 0}, {'ts': 1607859099, 'heat1': 119, 'heat2': 0, 'cool1': 0, 'cool2': 0, 'aux1': 19, 'aux2': 0, 'fc': 0}]
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 60.0
Cool setpoint is 90.0

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "POST /control HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.123.45:80
DEBUG:urllib3.connectionpool:http://192.168.123.45:80 "GET /query/info HTTP/1.1" 200 None
Heat setpoint is 74.0
Cool setpoint is 82.0
```

**Comment by hpeyerl** [comment]
Once you two have settled on something that makes both of you happy, let me know and I'll merge it. :)

**Comment by doug-hoffman** [comment]
I'm happy now. Last improvement, I promise.

**Comment by garbled1** [comment]
I like the new additions, I'm happy now too.

**Comment by hpeyerl** [comment]
I'll try to make some time to crank out a new release on Pypi in the next day or two.  I think I have to resurrect a container to do so.

**Comment by doug-hoffman** [comment]
Perfect! I plan to submit a PR to bump home assistant once that's done.

**Comment by garbled1** [comment]
If you do, can you add support for the additional sensors?

**Comment by doug-hoffman** [comment]
That's the plan, but separately, so the fix for the current temperature gets through quicker. I also plan to modernize the integration to support config flow for flexibility with sensor entity names. It's unlikely that I'll get to it in the next few days, as I'll be dividing my time between shoveling quite a bit of snow and troubleshooting the denonavr integration.

While you wait, enjoy some REST sensor magic:

```yaml
sensor:
  - platform: rest
    name: Thermostat Sensors
    json_attributes:
      - sensors
    resource: http://192.168.123.45/query/sensors
    value_template: "sensoring"
    scan_interval: 60
  - platform: template
    sensors:
      average_temperature:
        friendly_name: "Average Temperature"
        device_class: temperature
        unit_of_measurement: "°F"
        value_template: "{{ state_attr('sensor.thermostat_sensors', 'sensors')|selectattr('name','eq','Space Temp')|map(attribute='temp')|list|last|default('None') }}"
      thermostat_room_humidity:
        friendly_name: "Thermostat Room Humidity"
        device_class: humidity
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.thermostat_sensors', 'sensors')|selectattr('name','eq','Thermostat')|map(attribute='hum')|list|last|default('None') }}"
      wireless_temperature_battery_level:
        friendly_name: "Wireless Temperature Sensor Battery Level"
        device_class: battery
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.thermostat_sensors', 'sensors')|selectattr('name','eq','Sensor Name')|map(attribute='battery')|list|last|default('None') }}"
```

**Comment by hpeyerl** [comment]
Version bumped to 0.13 and uploaded to pypi.

**Pull request merged**
