### PR TITLE
Add Security/ Setpoint features

### PR DESCRIPTION
**Pull request by tbl-benjamin**
The library was missing the ability to turn on/off security features, i.e. setpoint limiting. With this PR, this functionality is added, including:
- turning on/off setpoint limiting
- choosing the cool and heat min and max, respectively

Additionally, a small refactor was done to increase the consistency of parsing the API response, resulting in less redundant code.

Note: Changes were tested on a Venstar T2100, which is otherwise compatible with this library.

### CODE REVIEW

**Comment by hpeyerl** [comment]
Looks great to me.  I can't actually test right now because my HA is in dire need of updating.

@garbled1 and/or @doug-hoffman  Are either of you able to quickly test this?  If neither of you have time, I'll just go ahead.

**Comment by doug-hoffman** [comment]
Doesn't seem to break anything in my HA dev environment, however, I can't confirm that set_security or set_setpoint_limits work on a T7900.

@tbl-benjamin, can you elaborate on what this changes on the thermostat and/or how to confirm that it was effective? I'm not seeing security, spMin, or spMax anywhere on developer.venstar.com. Calling set_security and set_setpoint_limits doesn't obviously affect the setpoint limits on my device.

**Comment by tbl-benjamin** [comment]
@doug-hoffman unfortunately, these settings are not documented on the website. To find them, I went on the Skyport Cloud portal, then Settings -> Security for the test thermostat. There you can see enabling/disabling setpoint limits, as well as the high and low setpoints. If you open your web browser's developer console (I use Chrome) and navigate to the Network tab, you can check the packets sent when you update any of these settings. This is how I found the `security`, `spMin`, and `spMax` settings, utilizing the same endpoint as the other settings. With `security` turned on, you can set your setpoints and try to raise your heat or lower your cooling past the points; it should not work. Additionally, you can check in the Venstar's settings that this mode and these setpoints are changed. For the T2100, [the advanced setup table on page 30](https://files.venstar.com/thermostats/explorermini/documents/T2100_manual.pdf) shows these settings as numbers 13-15.

**Comment by doug-hoffman** [comment]
@tbl-benjamin, I am not seeing the same parameters in Skyport as shown in your screenshot – I have secMin and secMax.

```json
{
    "ui_statScreenLockActive": 0,
    "ui_passCode": 1234,
    "ui_autoLockTimer": 60,
    "ui_secAllowMode": 0,
    "ui_secAllowSp": 0,
    "ui_secAllowAway": 0,
    "security": 1,
    "secMin": 117,
    "secMax": 133
}
````

I can change them in Skyport and see the change reflected on my thermostat screen. Calling set_security doesn't turn the limit on/off anywhere. If this does in fact work against the local API on your stat, it should be noted somewhere that these calls aren't supported on all models to avoid confusion.

**Comment by tbl-benjamin** [comment]
@doug-hoffman I did test this thoroughly on my stat; I can open another PR and make a note of this. Really wish Venstar had their entire API/ Cloud functionality documented.

**Comment by hpeyerl** [comment]
Maybe just update README.md?  We should maybe start some model-specific documentation sections.

**Pull request merged**
