### PR TITLE
Update for initial HASS integration

### PR DESCRIPTION
**Pull request by Cinntax**
My commits speak for themselves, but i added a few helper methods for the HASS component, SSL/Auth, and some additional error reporting.

### CODE REVIEW

**Comment by Cinntax** [comment]
Awesome- yeah good idea on holding off.  i'm actually struggling with the humidity setting right now. Adjustments will need to be made. I actually reached out to venstar on that portion of the API.  I'm not seeing what i'm expecting, and my attempts to set/change humidity have failed so far.

**Comment by hpeyerl** [comment]
Let me know how that goes.  That's something I've been meaning to do as well as play with the free-cooling.

**Comment by Cinntax** [comment]
I heard back from Venstar- they resolved the humidifier issues in the latest firmware.  As soon as i updated, all worked fine.

**Comment by hpeyerl** [comment]
Excellent.  

I've pushed to pypi: https://pypi.python.org/pypi/venstarcolortouch/0.2

**Comment by Cinntax** [comment]
Great!  I’ll get the hass component updated in my branch after work and re-push. How comfortable are you with testing from my dev branch? I’ll do some more testing, but want me to wait for you prior to my hass pull request?

**Comment by hpeyerl** [comment]
> On Jan 12, 2018, at 12:45 PM, Dan Cinnamon <notifications@github.com> wrote:
> 
> Great! I’ll get the hass component updated in my branch after work and re-push. How comfortable are you with testing from my dev branch? I’ll do some more testing, but want me to wait for you prior to my hass pull request?


I’m ok working on a hass dev branch.  My current hass instance is running from my own dev branch.  Only issue is that it’s out at my cottage so I’m not sure when I’ll be physically present out there next.  I don’t really want to mess with the thermostat while I’m not there in the winter.

So I’d say go ahead and do your hass stuff and I’ll catch up when I”m able.

**Pull request merged**
